package com.englishflow.community.entity;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import java.util.ArrayList;
import static org.junit.jupiter.api.Assertions.*;

class TopicTest {

    @Test
    void testNoArgsConstructor() {
        Topic topic = new Topic();
        assertNotNull(topic);
    }

    @Test
    void testSettersAndGetters() {
        Topic topic = new Topic();
        SubCategory subCategory = new SubCategory();
        LocalDateTime now = LocalDateTime.now();
        
        topic.setId(1L);
        topic.setTitle("Test Topic");
        topic.setContent("Test Content");
        topic.setUserId(100L);
        topic.setUserName("Test User");
        topic.setSubCategory(subCategory);
        topic.setViewsCount(50);
        topic.setReactionsCount(10);
        topic.setLikeCount(5);
        topic.setInsightfulCount(3);
        topic.setHelpfulCount(2);
        topic.setWeightedScore(100);
        topic.setIsTrending(true);
        topic.setIsPinned(false);
        topic.setIsLocked(false);
        topic.setPosts(new ArrayList<>());
        topic.setResourceType("PDF");
        topic.setResourceLink("http://example.com");
        topic.setIsAutoGenerated(false);
        topic.setCreatedAt(now);
        topic.setUpdatedAt(now);
        
        assertEquals(1L, topic.getId());
        assertEquals("Test Topic", topic.getTitle());
        assertEquals("Test Content", topic.getContent());
        assertEquals(100L, topic.getUserId());
        assertEquals("Test User", topic.getUserName());
        assertEquals(50, topic.getViewsCount());
        assertEquals(10, topic.getReactionsCount());
        assertTrue(topic.getIsTrending());
        assertFalse(topic.getIsPinned());
        assertFalse(topic.getIsLocked());
        assertEquals("PDF", topic.getResourceType());
        assertFalse(topic.getIsAutoGenerated());
    }

    @Test
    void testCalculateWeightedScore() {
        Topic topic = new Topic();
        topic.setLikeCount(5);
        topic.setInsightfulCount(3);
        topic.setHelpfulCount(2);
        
        topic.calculateWeightedScore();
        
        // Score = (5 * 1) + (3 * 2) + (2 * 3) = 17
        assertEquals(17, topic.getWeightedScore());
    }
}
