package com.englishflow.community.dto;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class CreateTopicRequestTest {

    @Test
    void testNoArgsConstructor() {
        CreateTopicRequest request = new CreateTopicRequest();
        assertNotNull(request);
    }

    @Test
    void testSettersAndGetters() {
        CreateTopicRequest request = new CreateTopicRequest();
        
        request.setTitle("Test Topic");
        request.setContent("Test Content");
        request.setUserId(100L);
        request.setUserName("Test User");
        request.setSubCategoryId(10L);
        request.setResourceType("PDF");
        request.setResourceLink("http://example.com/file.pdf");
        request.setIsAutoGenerated(false);
        
        assertEquals("Test Topic", request.getTitle());
        assertEquals("Test Content", request.getContent());
        assertEquals(100L, request.getUserId());
        assertEquals("Test User", request.getUserName());
        assertEquals(10L, request.getSubCategoryId());
        assertEquals("PDF", request.getResourceType());
        assertEquals("http://example.com/file.pdf", request.getResourceLink());
        assertFalse(request.getIsAutoGenerated());
    }

    @Test
    void testToString() {
        CreateTopicRequest request = new CreateTopicRequest();
        request.setTitle("Test");
        
        String toString = request.toString();
        assertTrue(toString.contains("Test"));
    }
}
