package com.englishflow.community.dto;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

class TopicDTOTest {

    @Test
    void testNoArgsConstructor() {
        TopicDTO dto = new TopicDTO();
        assertNotNull(dto);
    }

    @Test
    void testAllArgsConstructor() {
        LocalDateTime now = LocalDateTime.now();
        
        TopicDTO dto = new TopicDTO(
            1L, "Test Topic", "Content", 100L, "User Name", 10L,
            50, 10, 5, 3, 2, 100, true, false, false, 5,
            now, now, "PDF", "http://link.com", false
        );
        
        assertEquals(1L, dto.getId());
        assertEquals("Test Topic", dto.getTitle());
        assertEquals("Content", dto.getContent());
        assertEquals(100L, dto.getUserId());
        assertEquals("User Name", dto.getUserName());
        assertEquals(10L, dto.getSubCategoryId());
        assertEquals(50, dto.getViewsCount());
        assertEquals(10, dto.getReactionsCount());
        assertEquals(5, dto.getLikeCount());
        assertEquals(3, dto.getInsightfulCount());
        assertEquals(2, dto.getHelpfulCount());
        assertEquals(100, dto.getWeightedScore());
        assertTrue(dto.getIsTrending());
        assertFalse(dto.getIsPinned());
        assertFalse(dto.getIsLocked());
        assertEquals(5, dto.getPostsCount());
        assertEquals(now, dto.getCreatedAt());
        assertEquals(now, dto.getUpdatedAt());
        assertEquals("PDF", dto.getResourceType());
        assertEquals("http://link.com", dto.getResourceLink());
        assertFalse(dto.getIsAutoGenerated());
    }

    @Test
    void testSettersAndGetters() {
        TopicDTO dto = new TopicDTO();
        LocalDateTime now = LocalDateTime.now();
        
        dto.setId(2L);
        dto.setTitle("Updated Topic");
        dto.setContent("Updated Content");
        dto.setUserId(200L);
        dto.setUserName("Updated User");
        dto.setSubCategoryId(20L);
        dto.setViewsCount(100);
        dto.setReactionsCount(20);
        dto.setLikeCount(10);
        dto.setInsightfulCount(5);
        dto.setHelpfulCount(5);
        dto.setWeightedScore(200);
        dto.setIsTrending(false);
        dto.setIsPinned(true);
        dto.setIsLocked(true);
        dto.setPostsCount(10);
        dto.setCreatedAt(now);
        dto.setUpdatedAt(now);
        dto.setResourceType("VIDEO");
        dto.setResourceLink("http://video.com");
        dto.setIsAutoGenerated(true);
        
        assertEquals(2L, dto.getId());
        assertEquals("Updated Topic", dto.getTitle());
        assertEquals("Updated Content", dto.getContent());
        assertEquals(200L, dto.getUserId());
        assertEquals("Updated User", dto.getUserName());
        assertEquals(20L, dto.getSubCategoryId());
        assertEquals(100, dto.getViewsCount());
        assertEquals(20, dto.getReactionsCount());
        assertEquals(10, dto.getLikeCount());
        assertEquals(5, dto.getInsightfulCount());
        assertEquals(5, dto.getHelpfulCount());
        assertEquals(200, dto.getWeightedScore());
        assertFalse(dto.getIsTrending());
        assertTrue(dto.getIsPinned());
        assertTrue(dto.getIsLocked());
        assertEquals(10, dto.getPostsCount());
        assertEquals(now, dto.getCreatedAt());
        assertEquals(now, dto.getUpdatedAt());
        assertEquals("VIDEO", dto.getResourceType());
        assertEquals("http://video.com", dto.getResourceLink());
        assertTrue(dto.getIsAutoGenerated());
    }

    @Test
    void testEqualsAndHashCode() {
        LocalDateTime now = LocalDateTime.now();
        
        TopicDTO dto1 = new TopicDTO(
            1L, "Test", "Content", 100L, "User", 10L,
            50, 10, 5, 3, 2, 100, true, false, false, 5,
            now, now, "PDF", "link", false
        );
        TopicDTO dto2 = new TopicDTO(
            1L, "Test", "Content", 100L, "User", 10L,
            50, 10, 5, 3, 2, 100, true, false, false, 5,
            now, now, "PDF", "link", false
        );
        
        assertEquals(dto1, dto2);
        assertEquals(dto1.hashCode(), dto2.hashCode());
    }

    @Test
    void testToString() {
        TopicDTO dto = new TopicDTO();
        dto.setId(1L);
        dto.setTitle("Test Topic");
        
        String toString = dto.toString();
        assertTrue(toString.contains("Test Topic"));
        assertTrue(toString.contains("id=1"));
    }
}
