package com.englishflow.club.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateTopicRequest {
    private String title;
    private String content;
    private Long userId;
    private String userName;
    private Long subCategoryId;
    private String resourceType;
    private String resourceLink;
    private Boolean isAutoGenerated;
}
